version: "3"
services:
  todofront:
    image: todofront
    environment:
      - REACT_APP_API_HOST=todoback
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - todoback
  todoback:
    image: todoback
    restart: always
    ports:
      - 3001:3001
  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
    restart: always
    depends_on:
      - todofront
      - todoback
